---
- name: Ensure NFS utilities are installed.
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present
    update_cache: yes

- name: Template /etc/default/nfs-kernel-server on Debian
  ansible.builtin.template:
    src: templates/nfs-kernel-server.j2
    dest: /etc/default/nfs-kernel-server
    mode: 0644
    backup: 'no'
